### ISSUE TITLE
Support for multiple endpoints

### ISSUE THREAD

**Issue by creffett** [fsufitch/movie-meme-generator#1]
It would be nice if the meme generator could programatically expose multiple endpoints for different sets of movies, perhaps based on tags. Hypothetical config:
```
sources:
  sw1:
    video: resources/sw-ep1.mp4
    srt: resources/sw-ep1.srt
    tags: prequels, absolutely_terrible_movies
  sw2:
    video: resources/sw-ep2.mkv
    srt: resources/sw-ep2.srt
    tags: prequels
  ohgodwhy:
    video: resources/holidayspecial.avi
    srt: resources/holidayspecial.srt
    tags: absolutely_terrible_movies
```
which would then expose (webaddress)/meme/prequels and (webaddress)/meme/absolutely_terrible_movies, with the former serving sw1 and sw2 and the latter serving sw1 and the Holiday Special.
